from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("apps/<str:section>/", views.child_section, name="child_section"),
    path("messages/", views.messages_inbox, name="messages_inbox"),
    path("messages/<int:recipient_pk>/", views.message_thread, name="message_thread"),
    path("calls/incoming/", views.incoming_call_status, name="incoming_call_status"),
    path("calls/start/<int:recipient_pk>/<str:call_type>/", views.start_family_call, name="start_family_call"),
    path("calls/<int:pk>/", views.call_room, name="call_room"),
    path("calls/<int:pk>/accept/", views.accept_family_call, name="accept_family_call"),
    path("calls/<int:pk>/decline/", views.decline_family_call, name="decline_family_call"),
    path("calls/<int:pk>/end/", views.end_family_call, name="end_family_call"),
    path("calls/<int:pk>/token/", views.call_token, name="call_token"),
    path("calls/<int:pk>/status/", views.call_status, name="call_status"),
    path("login/", views.FamilyLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("health/", views.health, name="health"),
    path("sw.js", views.service_worker, name="service_worker"),
    path("notifications/subscribe/", views.subscribe_push, name="subscribe_push"),
    path("notifications/read/", views.read_notifications, name="read_notifications"),
    path("chores/<int:pk>/start/", views.start_chore, name="start_chore"),
    path("chores/<int:pk>/submit/", views.submit_chore, name="submit_chore"),
    path("goals/<int:pk>/submit/", views.submit_goal, name="submit_goal"),
    path("store/<int:pk>/buy/", views.buy_item, name="buy_item"),
    path("wallet/", views.wallet_page, name="wallet_page"),
    path("wallet/convert/", views.request_conversion, name="request_conversion"),
    path("wallet/convert-to-savings/", views.request_tokens_to_savings, name="request_tokens_to_savings"),
    path("wallet/token-cashout/", views.request_token_cashout, name="request_token_cashout"),
    path("wallet/cashout/", views.request_cashout, name="request_cashout"),
    path("wallet/spending/", views.request_spending_transfer, name="request_spending_transfer"),
    path("wallet/send/", views.send_family_transfer, name="send_family_transfer"),
    path("wallet/send-tokens/", views.send_token_gift, name="send_token_gift"),
    path("wallet/spend/", views.request_store_spend, name="request_store_spend"),
    path("wallet/goal/", views.save_savings_goal, name="save_savings_goal"),
    path("recap/dismiss/", views.dismiss_recap, name="dismiss_recap"),
    path("guardian/add/<str:model>/", views.guardian_create, name="guardian_create"),
    path("guardian/child-profile/", views.guardian_child_profile, name="guardian_child_profile"),
    path("guardian/edit/<str:model>/<int:pk>/", views.guardian_edit, name="guardian_edit"),
    path("guardian/toggle/<str:model>/<int:pk>/", views.guardian_toggle, name="guardian_toggle"),
    path("guardian/remove/<str:model>/<int:pk>/", views.guardian_remove, name="guardian_remove"),
    path("guardian/settings/", views.update_family_settings, name="update_family_settings"),
    path("guardian/communications/schedule/", views.guardian_communication_schedule, name="guardian_communication_schedule"),
    path("guardian/communications/<int:pk>/toggle/", views.guardian_toggle_communication_schedule, name="guardian_toggle_communication_schedule"),
    path("guardian/communications/<int:pk>/remove/", views.guardian_remove_communication_schedule, name="guardian_remove_communication_schedule"),
    path("rules/<str:model>/<int:pk>/acknowledge/", views.acknowledge_rule, name="acknowledge_rule"),
    path("guardian/schedule/approve/", views.dad_approve_schedule, name="dad_approve_schedule"),
    path("guardian/lockdown/", views.guardian_lockdown, name="guardian_lockdown"),
    path("guardian/star/", views.award_star, name="award_star"),
    path("guardian/award/", views.guardian_award, name="guardian_award"),
    path("guardian/deduct/", views.guardian_behavior_deduction, name="guardian_behavior_deduction"),
    path("guardian/balance/", views.dad_balance_adjustment, name="dad_balance_adjustment"),
    path("guardian/wallet-adjustment/", views.dad_balance_adjustment, name="guardian_wallet_adjustment"),
    path("guardian/review/<int:pk>/<str:decision>/", views.review_request, name="review_request"),
]
